import type { Metadata } from "next";
import localfont from "next/font/local";
import "./globals.css";
import Theme from "./theme";




const font = localfont({
  src: "./../public/JosefinSans-VariableFont_wght.ttf",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 
  return (
    <html lang="en">
      <Theme/>
      <body className={font.className}>{children}</body>
    </html>
  );
}
